"""trgm index for novels title

Revision ID: 5e8860d44244
Revises: dc05bf9d48af
Create Date: 2025-08-14 02:09:34.627354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e8860d44244"
down_revision: Union[str, Sequence[str], None] = "dc05bf9d48af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    op.drop_index(
        op.f("ix_novel_titles_search"), table_name="novels", postgresql_using="gin"
    )
    op.create_index(
        "ix_novel_title_trgm",
        "novels",
        [sa.literal_column("lower(title)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(title)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_novel_title_trgm",
        table_name="novels",
        postgresql_using="gin",
        postgresql_ops={"lower(title)": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_novel_titles_search"),
        "novels",
        [sa.literal_column("to_tsvector('russian'::regconfig, title::text)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
