"""obj_cover_name can be null

Revision ID: dc05bf9d48af
Revises: 853c3fa5ef2b
Create Date: 2025-08-12 23:19:56.975067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc05bf9d48af'
down_revision: Union[str, Sequence[str], None] = '853c3fa5ef2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novels', 'obj_cover_name',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novels', 'obj_cover_name',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
