"""column hashed_password ranamed to password

Revision ID: 853c3fa5ef2b
Revises: 26be06086d02
Create Date: 2025-08-12 02:41:29.017300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "853c3fa5ef2b"
down_revision: Union[str, Sequence[str], None] = "26be06086d02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("novels", sa.Column("obj_cover_name", sa.Uuid(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "password")
    op.drop_column("novels", "obj_cover_name")
    # ### end Alembic commands ###
