"""create novel table with gin index

Revision ID: 26be06086d02
Revises: 5d820c030e4a
Create Date: 2025-08-09 16:12:35.802820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26be06086d02"
down_revision: Union[str, Sequence[str], None] = "5d820c030e4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novels",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novels")),
    )
    op.create_index(
        "ix_novel_titles_search",
        "novels",
        [sa.literal_column("to_tsvector('russian'::regconfig, title)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_novel_titles_search", table_name="novels", postgresql_using="gin")
    op.drop_table("novels")
    # ### end Alembic commands ###
